### PR TITLE
feat(delete): Allow admin and org stewards to delete without pending …

### PR DESCRIPTION
**Pull request by mleeBoeing**
Code was outdated. This was never working. 

@blynch11p @cwilliams2017 @flesher1 @lsemesky @mannyrivera2010 @rkenyon1969 @skhtet @tdressel

### CODE REVIEW

**Comment by rkenyon1969** [comment]
@mleeBoeing - this fixes the function, but we need to address the code that uses this function to ensure we are making the correct comparison and achieving the desired results.

**Comment by mleeBoeing** [comment]
Changes not necessary. Seems to be working now for some reason.

**Comment by rkenyon1969** [comment]
@mleeBoeing - this is still broken. It seems to work because:

 o.shorName (undefined) === org.shortName (undefined).

Since this is a bug and outside scope of original task, I will create bug ticket for next sprint.

**Comment by rkenyon1969** [comment]
Bug ticket created (AMLNG-780) and added to upcoming sprint

**Pull request closed without merging**
