### PR TITLE
Notification endpoint update

### PR DESCRIPTION
**Pull request by lsemesky**
requires notificationEndpointUpdate backend branch to test

updated styling for notifications and added behavior where bell icon unread notification becomes read upon clicking.
When individual notification is clicked then it becomes unbolded to identify it has been interacted with. (don't worry I will squash this commit)

### CODE REVIEW

**Comment by blynch11p** [comment]
:+1:

**Comment by rkenyon1969** [comment]
Pulled, reviewed code and tested both branches successfully:
1. Unclicked notification count on bell disappears after clicking bell
2. Unclicked notification title appears bold
3. Clicked notification title appears unbold

:+1:

**Comment by rkenyon1969** [comment]
Found the following while reviewing code online:
> ozp-react-commons/app/js/components/notification/UserNotifications.jsx:

screen shot 2017-06-12 at 9 32 58 pm

I wasn't able to pull and test code again to see if this is related to Travis issue but thought it was worth noting.

**Comment by lsemesky** [comment]
@blynch11p  can I get a sanity check on the line I changed before I merge?

**Comment by blynch11p** [comment]
Looks good :+1:

**Pull request merged**
