### PR TITLE
feat(profile): add organizations within profile modal

### PR DESCRIPTION
**Pull request by mleeBoeing**
As a user, I want my organization to appear under the username in the Profile Modal so that I can confirm correct information.

Acceptance Criteria:
user organization will appear under the username and above email address on Profile Modal

### CODE REVIEW

**Comment by blynch11p** [comment]
It works, however, I'd make it stylistically look more like the Listings, rather than a floating bullet with no context.
screenshot from 2017-12-12 13-00-26

**Comment by mleeBoeing** [comment]
Added styling

**Comment by irizvifearless** [comment]
:+1:

**Comment by blynch11p** [comment]
👍

**Pull request merged**
