### PR TITLE
enhancement(privateListings): Updated private apps language Center 722

### PR DESCRIPTION
**Pull request by lsemesky**
@mannyrivera2010 @rkenyon1969 @skhtet 

for https://github.com/aml-development/ozp-center/issues/722

### CODE REVIEW

**Comment by rkenyon1969** [comment]
@lsemesky - why is agencies capitalized?

**Comment by lsemesky** [comment]
@rkenyon1969 I capitalized it because "Agency" was capitalized in the requirements. I am trying to track where the documentation requirements came from right now.

**Comment by skhtet** [comment]
👍

**Comment by lsemesky** [comment]
@rkenyon1969 Andrew collected the requirements during iteration planning. It doesn't have to be capitalized if you don't want it to. We also need to ask if they want other instances of the word "organization" to be replaced with "agency" and maybe confirm capitalization in the next iteration.

**Comment by rkenyon1969** [comment]
👍

**Pull request merged**
