### PR TITLE
JIRA-447 Add links to notifications

### PR DESCRIPTION
**Pull request by lsemesky**
Acceptance criteria: For the following notification types, the specified behavior should occur when clicking on a link in the notifications
SystemWide: None
AgencyWide: None
ListingReview: Click on link to go to reviews page
ListingPrivateStatus: None (since there is nothing to be taken to)
PendingDeletionRequest: ~~Go to delete tab for app~~ No action since apparently this is to let the app owner know their app was deleted
PendingDeletionCancellation: Go to my listings page
ListingSubmission: Go to admin tab for app
PeerBookmark: Other than existing add button the notification doesn't do anything
Category Subscription: Takes you to the new app in the category
TagSubscription: Takes you to the new app in the tag

Requires backend branch updateNotification
https://github.com/aml-development/ozp-backend/pull/355

### CODE REVIEW

**Comment by blynch11p** [comment]
I'll have to walk through some of these with you, maybe I'm overlooking an initial setup, or am using the wrong users, but here's my results:

SystemWide: None ✔️ 
AgencyWide: None ✔️ 
ListingReview: Click on link to go to reviews page ✔️ 
ListingPrivateStatus: None (since there is nothing to be taken to) ✔️ 
PendingDeletionRequest: Go to delete tab for app - ❌ - no notification received
PendingDeletionCancellation: Go to my listings page -  ✔️ 
ListingSubmission: Go to admin tab for app ✔️
PeerBookmark: Other than existing add button the notification doesn't do anything ✔️ 
Category Subscription: Takes you to the new app in the category - ❌ - no link in notification
TagSubscription: Takes you to the new app in the tag - ❌ - no link in notification

**Comment by lsemesky** [comment]
@blynch11p I was wrong about what is supposed to happen with a pending deletion request... apparently that is to let the owner know their app has been removed. It seems like we are missing a really useful notification type.
The test case for pending deletion request is as follows btw
Test Case:
        Logged on as jones
        Set Test Notification Listing to Pend for Deletion state
        Logged on as minitrue Org Content Steward- julia
        Approved the deletion
        Logged on as jones
        RESULTS The notification launched = Test Notification Listing listing was approved for deletion by steward

**Comment by rkenyon1969** [comment]
SystemWide: None :white_check_mark:
AgencyWide: None **(how do I test this?)**
ListingReview: Click on link to go to reviews page :white_check_mark:
ListingPrivateStatus: None (since there is nothing to be taken to) :white_check_mark:
PendingDeletionRequest: None :white_check_mark:
PendingDeletionCancellation: Go to my listings page :white_check_mark:
ListingSubmission: Go to admin tab for app :white_check_mark:
PeerBookmark: Other than existing add button the notification doesn't do anything :white_check_mark:
Category Subscription: Takes you to the new app in the category :no_entry_sign: 
**(bug - maybe due to my system; need to investigate)**
TagSubscription: Takes you to the new app in the tag :no_entry_sign: 
**(bug - maybe due to my system; need to investigate)**

**Comment by blynch11p** [comment]
On my latest test for subscriptions, I'm getting an error in the console when including this branch 
`TypeError: listing is null`on both center and in create listing
that I don't get if I have ozp-react-commons master.

This happens after subscribing to Category & Tag, and then creating a listing.  After the listing is created, and I assume the notification would be created, I refresh the page and the error displays in the console.

**Comment by lsemesky** [comment]
@blynch11p @rkenyon1969  the subscription notification issue was a backend issue. Make sure to pull latest (it is merged into master now so you can use that if you want)

**Comment by blynch11p** [comment]
Errors mentioned above are corrected.  Notifications are not sent after a user unsubscribes, as expected.

👍

**Comment by rkenyon1969** [comment]
Please don't merge until I've reviewed. - thank you,

**Comment by rkenyon1969** [comment]
1. pulled branch
2. review code
3. tested

:+1:

**Pull request merged**
