### PR TITLE
Initial commit to display time in Zulu and not EDT

### PR DESCRIPTION
**Pull request by mleeBoeing**
Time should now show in GMT instead of EDT.

### CODE REVIEW

**Comment by blynch11p** [comment]
Should this be military time? If yes, remove the ':', if no, well, it's showing as 24h.

**Comment by mleeBoeing** [comment]
Fixed

**Comment by blynch11p** [comment]
:+1:

**Comment by lsemesky** [comment]
Does it matter that we have (Z) and GMT? 
image

Otherwise PR looks like it does what it says and code looks good :+1:

**Comment by blynch11p** [comment]
@rkenyon1969, is displaying Z and GMT ok? We initially added Z for consistency.

**Comment by rkenyon1969** [comment]
- Zulu (Z) = GMT = UTC
- Customer would like to display all time in Zulu (Z)

**Comment by rkenyon1969** [comment]
https://www.timeanddate.com/worldclock/timezone/zulu

**Pull request merged**
